[package]
name    = "arcanum-graph"
version = "0.1.0"
edition = "2021"

[dependencies]
arcanum-core = { path = "../arcanum-core" }
async-trait  = { workspace = true }
tokio        = { workspace = true }
serde        = { workspace = true }
serde_json   = { workspace = true }
anyhow       = { workspace = true }
